name: Welfare
version: 6.3
main: welfare.welfare.Welfare
api-version: 1.17
authors: [ 3cxc ]
description: 一个轻量级的Minecraft 1.17.1福利插件
commands:
  welbf:
    description: 获得福利
  welver:
    description: 检查版本
  welgui:
    description: 打开主菜单
  welmusic:
    description: 获得音乐材质包
  welhelp:
    description: 获得命令帮助
  wel404:
    description: 自杀(假的)
  welkill:
    description: 自杀(假的)
  welGithub:
    description: 访问Github